data:
  train_dir: "data/train"
  val_dir: "data/val"
  img_size: 300
  num_workers: 2

model:
  backbone: "efficientnet_b3"
  pretrained: true
  dropout: 0.3
  num_classes: 82

training:
  batch_size: 32
  epochs: 25
  lr: 3.0e-4
  weight_decay: 1.0e-4
  label_smoothing: 0.1
  scheduler: "cosine"

logging:
  project: "plant-disease"
  entity: "hakobyananna2002-no-company"
  run_name: "efficientnet_b3_baseline"